# Generated by Django 4.2.6 on 2023-10-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fines', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='issued_fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fines.issuedfines'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
