# Generated by Django 4.2.6 on 2023-11-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_company_vehicles_vehicle_company_and_more'),
        ('fines', '0003_alter_transactions_issued_fine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedfines',
            name='vehicle_issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.vehicles'),
        ),
    ]
