# Generated by Django 4.2.6 on 2023-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0004_issuedfines_vehicle_issued_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fineclasses',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fineclasses',
            name='fine_name',
            field=models.CharField(max_length=50),
        ),
    ]
