# Generated by Django 4.2.6 on 2023-10-27 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FineClasses',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('fine_name', models.CharField(max_length=30)),
                ('amount_percent', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'fine_class',
                'verbose_name_plural': 'fine_classes',
                'db_table': 'fine_classes',
            },
        ),
        migrations.CreateModel(
            name='IssuedFines',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=10)),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'issued_fine',
                'verbose_name_plural': 'issued_fines',
                'db_table': 'issued_fines',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('card', 'Debit / Credit card'), ('upi', 'UPI'), ('netbanking', 'Netbanking'), ('NEFT', 'NEFT')], max_length=30)),
                ('issued_fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.issuedfines')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
            },
        ),
    ]
