# Generated by Django 4.2.6 on 2023-10-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_aadhar_no_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='aadhar_no',
        ),
    ]
