# Generated by Django 4.2.6 on 2023-10-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_id_user_aadhar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='company',
            field=models.CharField(default='BMW', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicles',
            name='model',
            field=models.CharField(default='i8', max_length=30),
            preserve_default=False,
        ),
    ]
