# Generated by Django 4.2.6 on 2023-10-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vehicles_company_vehicles_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='company',
            new_name='vehicle_company',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='model',
            new_name='vehicle_model',
        ),
    ]
